// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { ThemeProvider } from "../components/ui/theme-provider";
// import Header from "@/components/ui/header";
// import { ClerkProvider } from "@clerk/nextjs";
// import { dark } from "@clerk/themes"; // Import the dark theme

// const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
// const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "CareerForge AI",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <ClerkProvider
//       appearance={{
//         baseTheme: dark, // This forces the Clerk components into dark mode
//       }}
//     >
//       <html lang="en" suppressHydrationWarning>
//         <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//           <ThemeProvider
//             attribute="class"
//             defaultTheme="dark"
//             enableSystem
//             disableTransitionOnChange
//           >
//             <Header />
//             <main className="min-h-screen">{children}</main>

//             <footer className="bg-muted/50 py-12">
//               <div className="container mx-auto px-4 text-center text-gray-200">
//                 <p>Designed and Built for Professional Career Advancement.</p>
//                 <p className="text-sm mt-2 font-light">© 2026 AI Career Coach. All Rights Reserved.</p>
//               </div>
//             </footer>
//           </ThemeProvider>
//         </body>
//       </html>
//     </ClerkProvider>
//   );
// }


import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import Header from "@/components/ui/header";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { dark } from "@clerk/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AI Career Coach",
  description: "Advanced Career Coaching Tools",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang="en" suppressHydrationWarning>
        <head>
          <link rel="icon" href="/logo.png" sizes="any" />
        </head>
        <body className={`${inter.className} antialiased`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {/* The Grid sits behind everything */}
            <div className="grid-background" />

            <div className="flex flex-col min-h-screen">
              <Header />
              
              <main className="flex-grow">
                {children}
              </main>

              <Toaster richColors />

             <footer className="bg-muted/50 py-12">
              <div className="container mx-auto px-4 text-center text-gray-200">
                <p>Designed and Built for Professional Career Advancement.</p>
                <p className="text-sm mt-2 font-light">&copy; 2026 CareerForgeAI. All Rights Reserved.</p>
              </div>
            </footer>
            </div>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}